### ISSUE TITLE
2.1.8 tagged as 3.0.0

### ISSUE THREAD

**Issue by relan** [wistein/TransektCount#10]
Hi,

F-Droid maintainer here. Recent build of TransektCount failed because latest Git tag "3.0.0" does not match [versionName "2.1.8"](https://github.com/wistein/TransektCount/blob/3.0.0/transektcount/src/main/AndroidManifest.xml#L6). You should decided whether it's 3.0.0 or 2.1.8.

If it's 3.0.0:

* delete "3.0.0" tag,
* adjust versionName and versionCode,
* tag new commit as "3.0.0".

If it's actually 2.1.8:

* delete "3.0.0" tag,
* tag the same commit as "2.1.8".

**Comment by wistein** [comment]
Oops,
sorry for that.
Will tag the corrected version as 3.0.1

**Comment by mimi89999** [comment]
@wistein Thanks. I disabled `2.1.8` and added `3.0.1`. https://gitlab.com/fdroid/fdroiddata/commit/012cf64f

**Comment by relan** [comment]
Thank you both!
