### ISSUE TITLE
Add information about dev environment

### ISSUE THREAD

**Issue by hhirsch** [wistein/TransektCount#4]
For interested devs it might be useful to describe a basic stack to develop and test the application on.

**Comment by wistein** [comment]
Do you have a link to an example of such a description?

Thanks,

 

wistein

 

Von: Henry Hirsch [mailto:notifications@github.com] 
Gesendet: Samstag, 25. Februar 2017 11:24
An: wistein/TransektCount
Cc: Subscribed
Betreff: [wistein/TransektCount] Add information about dev environment (#4)

 

For interested devs it might be usefull to describe a basic stack to develop and test the application on.

**Comment by hhirsch** [comment]
https://github.com/GlPortal/glPortal/blob/master/COMPILE.md

**Comment by wistein** [comment]
Compile_TransektCount.md provided in docs.
