### ISSUE TITLE
Transekt Count shows Database problem while clicking on the option.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [wistein/TransektCount#9]
#### Expected behavior
While clicking on the option  shown in this image![IMG_20180325_132435.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521964710/gszdofd17rgqyfoodgvd.jpg),it must show some options. 

#### Actual behavior
While clicking on the option shown above in image, it shows Database problem. 

#### How to reproduce 
Install the app from f droid. 

Press on the option shown in the image. 

It shows database problem. 

* Browser: Transekt Count. 
* Version:2.1.6
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/YafwXgR45O4    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/transekt-count-shows-database-problem-while-clicking-on-the-option">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wistein** [comment]
Yes agree, there is a bug in handling the first use situation.

You have to prepare some steps before you can use the app for counting:
As described in the documentation and in the Help you have to set up a list of species to be counted before you can actually count any species. The app cannot work right from first start, as there is no database yet.

The app should allow you to create this, but here the bug blocks doing just this.

To help around, please copy one of the prepared databases from the docs directory in this repository to the root of your user space (/storage/emulated/0/). Then import this database with "Import DB".

After that the app should work as expected and you might edit or use the database within the app.

I will fix this asap. Thanks for testing.

**Comment by wistein** [comment]
Version 3.0.0 fixed it.
